# -*- coding: utf-8 -*-
"""train_test_val_split.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PtVn82Tmp306I1oGSN_oxzPd5674PXUf
"""

from google.colab import drive
drive.mount("/content/drive")

import os

# !scp /content/drive/MyDrive/bht_mudra.zip ./
# !unzip bht_mudra

try:
  os.mkdir('/content/drive/MyDrive/bht_mudra_train_test_split_2')
except:
  pass



try:
  os.mkdir('/content/drive/MyDrive/bht_mudra_train_test_split_2/train')
except:
  pass
try:
  os.mkdir('/content/drive/MyDrive/bht_mudra_train_test_split_2/test')
except:
  pass
try:
  os.mkdir('/content/drive/MyDrive/bht_mudra_train_test_split_2/val')
except:
  pass

import cv2
for dir in os.listdir('/content/drive/MyDrive/bht_mudra_class_5'):
  l=0
  try:
    os.mkdir('/content/drive/MyDrive/bht_mudra_train_test_split_2/train/'+dir)
  except:
    pass
  try:
    os.mkdir('/content/drive/MyDrive/bht_mudra_train_test_split_2/test/'+dir)
  except:
    pass
  try:
    os.mkdir('/content/drive/MyDrive/bht_mudra_train_test_split_2/val/'+dir)
  except:
    pass
  for file in os.listdir('/content/drive/MyDrive/bht_mudra_class_5/'+dir):
    l+=1
  k=0

  try:
    for file in os.listdir('/content/drive/MyDrive/bht_mudra_class_5/'+dir):
      if(k<=l*0.8):
        img = cv2.imread('/content/drive/MyDrive/bht_mudra_class_5/'+dir+'/'+file)
        cv2.imwrite('/content/drive/MyDrive/bht_mudra_train_test_split_2/train/'+dir+'/'+file,img)
      elif(k<=l*0.9):
        img = cv2.imread('/content/drive/MyDrive/bht_mudra_class_5/'+dir+'/'+file)
        cv2.imwrite('/content/drive/MyDrive/bht_mudra_train_test_split_2/val/'+dir+'/'+file,img)
      else:
        img = cv2.imread('/content/drive/MyDrive/bht_mudra_class_5/'+dir+'/'+file)
        cv2.imwrite('/content/drive/MyDrive/bht_mudra_train_test_split_2/test/'+dir+'/'+file,img)
      k+=1
  except:
      print(file)


  # for

p=0
for i in os.listdir('/content/drive/MyDrive/bht_mudra_train_test_split_2/train/'):
  for j in os.listdir('/content/drive/MyDrive/bht_mudra_train_test_split_2/train/'+i):
    p+=1

for i in os.listdir('/content/drive/MyDrive/bht_mudra_train_test_split_2/test/'):
  for j in os.listdir('/content/drive/MyDrive/bht_mudra_train_test_split_2/test/'+i):
    p+=1

for i in os.listdir('/content/drive/MyDrive/bht_mudra_train_test_split_2/val/'):
  for j in os.listdir('/content/drive/MyDrive/bht_mudra_train_test_split_2/val/'+i):
    p+=1
print(p)

